import { test, expect, type Page } from '@playwright/test';
test.use({ channel: 'msedge', viewport: { width: 1440, height: 960 } });
const read = (page: Page) => page.evaluate(() => JSON.parse(localStorage.getItem('taller-project-v1')!));
async function front(page: Page) { await page.getByLabel('Vista', { exact: true }).selectOption('Frontal'); await page.waitForTimeout(1500); }
async function scale(page: Page) { const a = (await page.locator('.ruler-label').filter({ hasText: /^0$/ }).boundingBox())!, b = (await page.locator('.ruler-label').filter({ hasText: /^1000$/ }).first().boundingBox())!; return Math.abs(b.x + b.width / 2 - a.x - a.width / 2) / 1000; }
async function precise(page: Page, label: string, value: number) { const d = page.locator('details'); if (await d.getAttribute('open') === null)
    await d.locator('summary').click(); await page.getByLabel(label, { exact: true }).fill(String(value)); await page.getByLabel(label, { exact: true }).press('Enter'); }
function consoleErrors(page: Page) { const errors: string[] = []; page.on('pageerror', e => errors.push(e.message)); page.on('console', m => { if (m.type() === 'error')
    errors.push(m.text()); }); return errors; }
test('corte visual, precisión, recorte, historial y persistencia', async ({ page }) => {
    const errors = consoleErrors(page);
    await page.goto('http://127.0.0.1:5173');
    await page.locator('.material-card').first().click();
    await front(page);
    const original = await read(page);
    await page.getByRole('button', { name: '✂ Cortar', exact: true }).click();
    await expect(page.locator('.cut-measure-label')).toHaveText('1500 mm | 1500 mm');
    const px = await scale(page), label = (await page.locator('.cut-measure-label').boundingBox())!;
    const handle = { x: label.x + label.width / 2, y: label.y + label.height / 2 + 90 * px };
    await page.mouse.move(handle.x, handle.y);
    await page.mouse.down();
    await page.mouse.move(handle.x - 1002 * px, handle.y, { steps: 30 });
    for (let step = 1; step <= 12 && (await page.locator('.cut-measure').textContent()) !== '500 mm | 2500 mm'; step++)
        await page.mouse.move(handle.x - (1002 + step * 2) * px, handle.y);
    await page.mouse.up();
    await expect(page.locator('.cut-measure')).toHaveText('500 mm | 2500 mm');
    expect(await read(page)).toEqual(original);
    await page.keyboard.press('ArrowLeft');
    await expect(page.locator('.cut-measure')).toHaveText('499 mm | 2501 mm');
    await page.keyboard.press('ArrowRight');
    await page.keyboard.press('Shift+ArrowRight');
    await expect(page.locator('.cut-measure')).toHaveText('510 mm | 2490 mm');
    await page.locator('.cut-measure-label').click();
    await page.getByLabel('Medida de corte').fill('720');
    await page.getByLabel('Medida de corte').press('Enter');
    await expect(page.locator('.cut-measure')).toHaveText('720 mm | 2280 mm');
    await page.screenshot({ path: 'tests/cut-preview.png' });
    await page.getByRole('button', { name: '✓ Confirmar corte' }).click();
    const first = await read(page);
    expect(first.pieces.map((p: any) => p.length)).toEqual([720, 2280]);
    expect(first.pieces[0].stockId).toBe(first.pieces[1].stockId);
    expect(first.cuts).toHaveLength(1);
    expect(first.stocks[0].length).toBe(3000);
    expect(first.pieces.every((p: any) => p.isCut && p.color !== original.pieces[0].color)).toBe(true);
    // Move each independently, then undo those moves; the next undo restores the whole original.
    await precise(page, 'Posición Y', 150);
    expect((await read(page)).pieces[1].position).toEqual(first.pieces[1].position);
    await page.keyboard.press('Control+z');
    await page.locator('.piece-select').nth(1).click();
    await precise(page, 'Posición Y', 250);
    expect((await read(page)).pieces[0].position).toEqual(first.pieces[0].position);
    await page.keyboard.press('Control+z');
    await page.keyboard.press('Control+z');
    expect(await read(page)).toEqual(original);
    await page.keyboard.press('Control+Shift+z');
    expect(await read(page)).toEqual(first);
    await page.locator('.piece-select').nth(1).click();
    await page.getByRole('button', { name: '✂ Cortar', exact: true }).click();
    await page.locator('.cut-measure').click();
    await page.getByLabel('Medida de corte').fill('450');
    await page.getByLabel('Medida de corte').press('Enter');
    await page.getByRole('button', { name: '✓ Confirmar corte' }).click();
    const second = await read(page);
    expect(second.pieces.map((p: any) => p.length)).toEqual([720, 450, 1830]);
    expect(second.cuts).toHaveLength(2);
    expect(new Set(second.pieces.map((p: any) => p.color)).size).toBe(1);
    await page.keyboard.press('Control+z');
    expect(await read(page)).toEqual(first);
    await page.keyboard.press('Control+Shift+z');
    expect(await read(page)).toEqual(second);
    await page.reload();
    await expect(page.locator('.piece-row')).toHaveCount(3);
    expect(await read(page)).toEqual(second);
    await page.locator('.piece-select').first().click();
    await page.getByRole('button', { name: '✂ Cortar', exact: true }).click();
    await page.keyboard.press('Escape');
    await expect(page.locator('.cut-bar')).toHaveCount(0);
    expect(await read(page)).toEqual(second);
    expect(errors).toEqual([]);
});
for (const sign of [1, -1])
    test(`agarre del extremo ${sign === 1 ? 'derecho' : 'izquierdo'} y snap`, async ({ page }) => {
        const errors = consoleErrors(page);
        await page.goto('http://127.0.0.1:5173');
        await page.locator('.material-card').first().click();
        await page.locator('.material-card').nth(2).click();
        await precise(page, 'Rotación Z', 90);
        await precise(page, 'Posición X', sign * 1700);
        await precise(page, 'Posición Y', 1200);
        await page.locator('.piece-select').first().click();
        await front(page);
        const before = await read(page), tag = (await page.locator('.piece-code-tag').boundingBox())!, px = await scale(page);
        const grab = { x: tag.x + tag.width / 2 + sign * 1400 * px, y: tag.y + tag.height / 2 + 259 * px };
        await page.mouse.move(grab.x, grab.y);
        await page.mouse.down();
        await page.mouse.move(grab.x + sign * 174 * px, grab.y, { steps: 25 });
        await page.screenshot({ path: `tests/grab-during-${sign}.png` });
        await expect(page.locator('.snap-tag')).toContainText('Caras unidas');
        await page.mouse.up();
        const after = await read(page);
        expect(after.pieces[0].position[0]).toBeCloseTo(sign * 180, 4);
        expect(after.pieces[1]).toEqual(before.pieces[1]);
        await page.keyboard.press('Control+z');
        expect(await read(page)).toEqual(before);
        await page.keyboard.press('Control+Shift+z');
        expect(await read(page)).toEqual(after);
        expect(errors).toEqual([]);
    });
test('pieza cortada se separa, hace snap y admite otro corte girada', async ({ page }) => {
    const errors = consoleErrors(page);
    await page.goto('http://127.0.0.1:5173');
    await page.locator('.material-card').first().click();
    await front(page);
    await page.getByRole('button', { name: '✂ Cortar', exact: true }).click();
    await page.locator('.cut-measure').click();
    await page.getByLabel('Medida de corte').fill('720');
    await page.getByLabel('Medida de corte').press('Enter');
    await page.getByRole('button', { name: '✓ Confirmar corte' }).click();
    const first = await read(page), px = await scale(page);
    let tag = (await page.locator('.piece-code-tag').boundingBox())!;
    let grab = { x: tag.x + tag.width / 2 + 330 * px, y: tag.y + tag.height / 2 + 259 * px };
    await page.mouse.move(grab.x, grab.y);
    await page.mouse.down();
    await page.mouse.move(grab.x - 160 * px, grab.y, { steps: 20 });
    await page.mouse.up();
    expect((await read(page)).pieces[0].position[0]).toBeLessThan(first.pieces[0].position[0] - 120);
    expect((await read(page)).pieces[1]).toEqual(first.pieces[1]);
    tag = (await page.locator('.piece-code-tag').boundingBox())!;
    grab = { x: tag.x + tag.width / 2 + 330 * px, y: tag.y + tag.height / 2 + 259 * px };
    await page.mouse.move(grab.x, grab.y);
    await page.mouse.down();
    await page.mouse.move(grab.x + 152 * px, grab.y, { steps: 25 });
    await expect(page.locator('.snap-tag')).toContainText('Caras unidas');
    await page.mouse.up();
    expect((await read(page)).pieces[0].position[0]).toBeCloseTo(first.pieces[0].position[0], 4);
    await precise(page, 'Rotación Z', 45);
    const rotated = await read(page);
    await page.getByRole('button', { name: '✂ Cortar', exact: true }).click();
    await page.locator('.cut-measure').click();
    await page.getByLabel('Medida de corte').fill('300.5');
    await page.getByLabel('Medida de corte').press('Enter');
    await expect(page.locator('.cut-measure')).toHaveText('300.5 mm | 419.5 mm');
    await page.keyboard.press('Enter');
    const result = await read(page);
    expect(result.pieces.map((p: any) => p.length)).toEqual([300.5, 419.5, 2280]);
    expect(result.pieces[0].rotation).toEqual([0, 0, 45]);
    expect(result.pieces[1].rotation).toEqual([0, 0, 45]);
    expect(result.pieces[1].position[0] - result.pieces[0].position[0]).toBeCloseTo(360 / Math.sqrt(2), 5);
    expect(result.pieces[1].position[1] - result.pieces[0].position[1]).toBeCloseTo(360 / Math.sqrt(2), 5);
    await page.keyboard.press('Control+z');
    expect(await read(page)).toEqual(rotated);
    await page.keyboard.press('Control+Shift+z');
    expect(await read(page)).toEqual(result);
    expect(errors).toEqual([]);
});
test('tablero admite corte recto y cancelar no modifica el proyecto', async ({ page }) => {
    const errors = consoleErrors(page);
    await page.goto('http://127.0.0.1:5173');
    await page.locator('.material-card').nth(3).click();
    const original = await read(page);
    await page.getByRole('button', { name: '✂ Cortar', exact: true }).click();
    await expect(page.locator('.cut-measure')).toHaveText('1220 × 1220 × 18 mm | 1220 × 1220 × 18 mm');
    await page.getByRole('button', { name: '✕ Cancelar' }).click();
    expect(await read(page)).toEqual(original);
    await page.getByRole('button', { name: '✂ Cortar', exact: true }).click();
    await page.locator('.cut-measure').click();
    await page.getByLabel('Medida de corte').fill('0');
    await expect(page.getByRole('button', { name: '✓ Confirmar corte' })).toBeDisabled();
    await page.getByLabel('Medida de corte').fill('1000');
    await page.getByLabel('Medida de corte').press('Enter');
    await page.getByRole('button', { name: '✓ Confirmar corte' }).click();
    const result = await read(page);
    expect(result.pieces.map((p: any) => [p.length, p.width, p.height])).toEqual([[1000, 1220, 18], [1440, 1220, 18]]);
    expect(result.stocks[0].catalogMaterialId).toBe('mdf-18');
    expect(errors).toEqual([]);
});
