import { test, expect } from '@playwright/test';
test.use({ channel: 'msedge', viewport: { width: 1440, height: 960 } });
test('flujo completo de Fase 1', async ({ page }) => {
    const errors: string[] = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('console', m => { if (m.type() === 'error')
        errors.push(m.text()); });
    await page.goto('http://127.0.0.1:5173');
    await expect(page.locator('canvas')).toBeVisible();
    await page.waitForTimeout(1600);
    const read = () => page.evaluate(() => JSON.parse(localStorage.getItem('taller-project-v1') || '{"pieces":[]}'));
    await page.locator('.material-card').first().dragTo(page.locator('canvas'), { targetPosition: { x: 420, y: 350 } });
    await expect.poll(async () => (await read()).pieces.length).toBe(1);
    await expect(page.locator('.dimension-tag')).toHaveText(['Largo 3000 mm','Ancho 100 mm','Espesor 18 mm']);
    await page.screenshot({ path: 'tests/editor-initial.png' });
    // Cancelled drag must not add a piece.
    await page.locator('.material-card').nth(1).dragTo(page.locator('header'));
    expect((await read()).pieces.length).toBe(1);
    await page.getByText('Ajuste preciso · mm y grados').click();
    await page.getByLabel('Posición Y').fill('720');
    await page.getByLabel('Posición Y').press('Enter');
    await expect.poll(async () => (await read()).pieces[0].position[1]).toBe(720);
    await page.getByLabel('Rotación Z').fill('90');
    await page.getByLabel('Rotación Z').press('Enter');
    await expect.poll(async () => (await read()).pieces[0].rotation[2]).toBe(90);
    await page.getByRole('button', { name: '↶ Deshacer' }).click();
    expect((await read()).pieces[0].rotation[2]).toBe(0);
    await page.getByRole('button', { name: '↷ Rehacer' }).click();
    expect((await read()).pieces[0].rotation[2]).toBe(90);
    await page.locator('.piece-select').first().click();
    await page.getByRole('button', { name: '⧉ Duplicar' }).first().click();
    expect((await read()).pieces.length).toBe(2);
    const ps = (await read()).pieces;
    expect(ps[0].id).not.toBe(ps[1].id);
    expect(ps[0].length).toBe(ps[1].length);
    await page.getByRole('button', { name: '♙ Bloquear' }).click();
    expect((await read()).pieces[1].isLocked).toBe(true);
    await page.getByText('Ajuste preciso · mm y grados').click();
    await expect(page.getByLabel('Posición X')).toBeDisabled();
    await page.getByRole('button', { name: '◌ Ocultar', exact: true }).click();
    expect((await read()).pieces[1].isHidden).toBe(true);
    await page.getByRole('button', { name: '◉ Mostrar', exact: true }).click();
    expect((await read()).pieces[1].isHidden).toBe(false);
    await page.getByRole('button', { name: '♧ Desbloquear' }).click();
    for (const view of ['Frontal', 'Posterior', 'Izquierda', 'Derecha', 'Superior', 'Isométrica']) {
        await page.getByLabel('Vista', { exact: true }).selectOption(view);
        await page.waitForTimeout(300);
    }
    await page.reload();
    await expect(page.locator('.piece-row')).toHaveCount(2);
    expect((await read()).pieces[1].rotation[2]).toBe(90);
    await page.locator('.piece-select').nth(1).click();
    await page.getByRole('button', { name: '× Eliminar', exact: true }).first().click();
    expect((await read()).pieces.length).toBe(1);
    await page.keyboard.press('Control+z');
    expect((await read()).pieces.length).toBe(2);
    await page.getByLabel('Acoplar Materiales').selectOption('bottom');
    await expect(page.locator('.dock-bottom')).toBeVisible();
    await page.getByLabel('Acoplar Materiales').selectOption('float');
    await expect(page.locator('.dock-float')).toBeVisible();
    await page.getByRole('button', { name: 'Cerrar Materiales' }).click();
    await page.getByRole('button', { name: '＋ Materiales', exact: true }).click();
    await page.getByLabel('Acoplar Materiales').selectOption('left');
    await page.getByRole('button', { name: '＋ Nuevo' }).click();
    expect((await read()).pieces.length).toBe(0);
    await page.keyboard.press('Control+z');
    expect((await read()).pieces.length).toBe(2);
    await page.screenshot({ path: 'tests/editor-final.png' });
    expect(errors).toEqual([]);
});
