import { test, expect, type Page } from '@playwright/test';
test.use({ channel: 'msedge', viewport: { width: 1440, height: 960 } });
const read = (page: Page) => page.evaluate(() => JSON.parse(localStorage.getItem('taller-project-v1')!));
const view = (page: Page, name: string) => page.getByRole('group', { name: 'Vista principal', exact: true }).getByRole('button', { name, exact: true }).click();
async function cut(page: Page, value: number, horizontal = false) {
    await page.getByRole('button', { name: '✂ Cortar', exact: true }).click();
    if (horizontal) await page.getByRole('button', { name: 'Corte horizontal ↔', exact: true }).click();
    await page.locator('.cut-measure').click();
    await page.getByLabel('Medida de corte').fill(String(value));
    await page.getByLabel('Medida de corte').press('Enter');
    await page.getByRole('button', { name: '✓ Confirmar corte', exact: true }).click();
}
test('propuesta independiente: sobrantes, compras, configuración, desactualización, historial y persistencia', async ({ page }) => {
    test.setTimeout(90000);
    const errors: string[] = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
    await page.goto('http://127.0.0.1:5173');
    await page.locator('.material-card').first().click(); await cut(page, 720);
    await page.locator('.material-card').first().click(); await cut(page, 450);
    const original = await read(page);
    await view(page, 'Fabricación');
    await expect(page.getByRole('button', { name: 'Plan actual', exact: true })).toHaveAttribute('aria-pressed', 'true');
    const actualPlan = await page.locator('.stock-plan').innerText();
    await page.getByLabel('Ancho de corte de sierra (kerf)', { exact: true }).fill('3');
    await page.getByLabel('Ancho de corte de sierra (kerf)', { exact: true }).press('Enter');
    await page.getByRole('button', { name: 'Optimizar material', exact: true }).click();
    await expect(page.locator('.optimization-shopping')).toContainText('Sobrantes reutilizados');
    let proposed = await read(page);
    expect(proposed.optimizedPlan.stocks).toHaveLength(1);
    expect(proposed.optimizedPlan.stocks[0].supply.kind).toBe('offcut');
    expect(proposed.pieces).toEqual(original.pieces); expect(proposed.stocks).toEqual(original.stocks); expect(proposed.cuts).toEqual(original.cuts);
    await expect(page.locator('.optimized-cut-order')).toContainText('Cortar A2 — 720 mm · sierra 3 mm');
    await page.screenshot({ path: 'tests/optimization-offcut.png' });
    await page.getByLabel('Considerar sobrantes existentes', { exact: true }).uncheck();
    await expect(page.locator('.stale-plan')).toContainText('Plan desactualizado');
    await page.getByRole('button', { name: 'Optimizar material', exact: true }).click();
    await expect(page.locator('.stale-plan')).toHaveCount(0);
    await expect(page.locator('.optimization-shopping')).toContainText('1 × Pino · 3000 × 100 × 18 mm');
    await page.getByRole('button', { name: 'Plan actual', exact: true }).click();
    expect(await page.locator('.stock-plan').innerText()).toBe(actualPlan);
    await view(page, 'Diseño');
    await page.locator('.piece-select').first().click();
    await cut(page, 300); // Changes required dimensions and creates another reusable descendant.
    const changed = await read(page);
    await view(page, 'Fabricación');
    await page.getByRole('button', { name: 'Plan optimizado · desactualizado', exact: true }).click();
    await expect(page.locator('.stale-plan')).toBeVisible();
    await page.getByRole('button', { name: 'Optimizar material', exact: true }).click();
    await expect(page.locator('.stale-plan')).toHaveCount(0);
    proposed = await read(page);
    expect(proposed.pieces).toEqual(changed.pieces);
    expect(proposed.optimizedPlan.stocks[0].placements.map((p: any) => p.piece.length).sort((a: number, b: number) => a - b)).toEqual([300, 450]);
    await page.getByLabel('Permitir rotación de piezas: 90°', { exact: true }).uncheck();
    await expect(page.locator('.stale-plan')).toBeVisible();
    await page.keyboard.press('Control+z');
    await expect(page.locator('.stale-plan')).toHaveCount(0);
    await page.keyboard.press('Control+Shift+z');
    await expect(page.locator('.stale-plan')).toBeVisible();
    await page.getByRole('button', { name: '▣ Guardar', exact: true }).click();
    const saved = await read(page);
    await page.reload();
    await expect(page.locator('.piece-row')).toHaveCount(5);
    expect(await read(page)).toEqual(saved);
    await view(page, 'Fabricación');
    await page.getByRole('button', { name: 'Plan optimizado · desactualizado', exact: true }).click();
    await expect(page.locator('.stale-plan')).toBeVisible();
    await expect(page.getByLabel('Permitir rotación de piezas: 90°', { exact: true })).not.toBeChecked();
    await page.getByRole('button', { name: 'Optimizar material', exact: true }).click();
    await expect(page.locator('.stale-plan')).toHaveCount(0);
    await page.screenshot({ path: 'tests/optimization-new.png' });
    expect(errors).toEqual([]);
});

test('hojas: aprovecha una pieza girada 90° y conserva el resultado al recargar', async ({ page }) => {
    const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto('http://127.0.0.1:5173');
    await page.locator('.material-card').nth(3).click();
    // 1200 x 700 only fits the 1000 x 1220 offcut when turned 90 degrees.
    // The other remaining rectangles (1440 x 520 and 240 x 700) cannot hold it.
    await cut(page, 1440); await cut(page, 700, true); await cut(page, 1200);
    await view(page, 'Fabricación');
    await page.getByLabel('Ancho de corte de sierra (kerf)', { exact: true }).fill('3');
    await page.getByLabel('Ancho de corte de sierra (kerf)', { exact: true }).press('Enter');
    await page.getByRole('button', { name: 'Optimizar material', exact: true }).click();
    const result = await read(page);
    expect(result.optimizedPlan.stocks.every((s: any) => s.supply.sheet)).toBe(true);
    expect(result.optimizedPlan.unplaced).toHaveLength(0);
    expect(result.optimizedPlan.stocks.some((s: any) => s.placements.some((p: any) => p.rotated))).toBe(true);
    await expect(page.locator('.optimized-diagram')).toBeVisible();
    await expect(page.locator('.optimized-stock')).toContainText('Giro 90°');
    await page.screenshot({ path: 'tests/optimization-sheet.png' });
    await page.getByLabel('Permitir rotación de piezas: 90°', { exact: true }).uncheck();
    await page.getByRole('button', { name: 'Optimizar material', exact: true }).click();
    expect((await read(page)).optimizedPlan.stocks[0].supply.kind).toBe('new');
    await page.getByLabel('Permitir rotación de piezas: 90°', { exact: true }).check();
    await page.getByRole('button', { name: 'Optimizar material', exact: true }).click();
    await page.reload(); await view(page, 'Fabricación');
    await page.getByRole('button', { name: 'Plan optimizado', exact: true }).click();
    expect((await read(page)).optimizedPlan).toEqual(result.optimizedPlan);
    await expect(page.locator('.stale-plan')).toHaveCount(0);
    expect(errors).toEqual([]);
});
