import { test, expect } from '@playwright/test';
test.use({ channel: 'msedge', viewport: { width: 1440, height: 960 } });
test('paneles móviles, acoplamiento, tamaño y configuración', async ({ page }) => {
    const errors: string[] = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('console', m => { if (m.type() === 'error')
        errors.push(m.text()); });
    await page.goto('http://127.0.0.1:5173');
    await page.waitForTimeout(500);
    const panel = page.locator('.panel').filter({ has: page.getByLabel('Acoplar Materiales') });
    const before = (await panel.boundingBox())!;
    const handle = await page.getByRole('separator', { name: 'Redimensionar Materiales' }).boundingBox();
    await page.mouse.move(handle!.x + 3, 300);
    await page.mouse.down();
    await page.mouse.move(handle!.x + 53, 300, { steps: 5 });
    await page.mouse.up();
    expect((await panel.boundingBox())!.width).toBeGreaterThan(before.width + 40);
    await page.getByLabel('Acoplar Materiales').selectOption('float');
    const floating = (await panel.boundingBox())!;
    await page.mouse.move(floating.x + 80, floating.y + 24);
    await page.mouse.down();
    await page.mouse.move(floating.x + 180, floating.y + 84, { steps: 6 });
    await page.mouse.up();
    expect((await panel.boundingBox())!.x).toBeGreaterThan(floating.x + 90);
    await page.getByLabel('Acoplar Materiales').selectOption('left');
    const heading = panel.locator('.panel-heading');
    const bounds = (await heading.boundingBox())!;
    await page.mouse.move(bounds.x + 80, bounds.y + 24);
    await page.mouse.down();
    await page.mouse.move(bounds.x + 150, bounds.y + 80, { steps: 8 });
    await page.mouse.move(850, 700, { steps: 8 });
    await expect(page.locator('.target-bottom')).toBeVisible();
    const drop = (await page.locator('.target-bottom').boundingBox())!;
    await page.mouse.move(drop.x + drop.width / 2, drop.y + 30, { steps: 10 });
    await page.mouse.up();
    await expect(panel).toHaveClass(/dock-bottom/);
    await page.getByRole('button', { name: '⚙ Configuración' }).click();
    await page.getByLabel('Cuadrícula y referencias (mm)').uncheck();
    await expect(page.locator('.ruler-label')).toHaveCount(0);
    await page.getByLabel('Cuadrícula y referencias (mm)').check();
    await expect(page.locator('.ruler-label')).toHaveCount(17);
    await page.getByLabel('Sombras suaves').uncheck();
    await page.getByRole('button', { name: 'Restablecer paneles' }).click();
    await expect(panel).toHaveClass(/dock-left/);
    expect(errors).toEqual([]);
});
