import { test, expect, type Page } from '@playwright/test';
test.use({channel:'msedge',viewport:{width:1440,height:1000}});
const read=(page:Page)=>page.evaluate(()=>JSON.parse(localStorage.getItem('taller-project-v1')!));
const view=(page:Page,name:string)=>page.getByRole('group',{name:'Vista principal',exact:true}).getByRole('button',{name,exact:true}).click();
async function cut(page:Page,value:number,rip=false){await page.getByRole('button',{name:'✂ Cortar',exact:true}).click();if(rip)await page.getByRole('button',{name:/Longitudinal · ancho|Corte horizontal ↔/}).click();await page.locator('.cut-measure').click();await page.getByLabel('Medida de corte',{exact:true}).fill(String(value));await page.getByLabel('Medida de corte',{exact:true}).press('Enter');await page.getByRole('button',{name:'✓ Confirmar corte',exact:true}).click();}
test('fase 7: cortar, repetir, acabados, unión, optimizar, PDF, imprimir y recargar',async({page})=>{
 test.setTimeout(120000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:5173');await page.locator('.material-card').first().click();await cut(page,720);await cut(page,40,true);
 await page.locator('.material-card').first().click();await page.keyboard.press('q');let project=await read(page);expect(project.cuts).toHaveLength(3);expect(project.cuts[2].axis).toBe('width');expect(project.cuts[2].offset).toBe(40);
 await page.getByRole('button',{name:'◎ Perforar',exact:true}).click();await page.getByText('Posición exacta / cara',{exact:true}).click();await page.getByLabel('Centro horizontal (mm)',{exact:true}).fill('100');await page.getByLabel('Centro vertical (mm)',{exact:true}).fill('20');await page.getByLabel('Diámetro (mm)',{exact:true}).fill('8');await page.getByRole('button',{name:'Confirmar operación',exact:true}).click();
 await page.getByRole('button',{name:'⌒ Formas curvas',exact:true}).click();await page.getByLabel('Radio (mm)',{exact:true}).fill('10');await page.getByRole('button',{name:'Confirmar operación',exact:true}).click();
 await page.getByRole('button',{name:'✂ Cortar',exact:true}).click();await page.getByRole('button',{name:'Corte angular',exact:true}).click();await page.getByLabel('Posición de corte (mm)',{exact:true}).fill('500');await page.getByRole('button',{name:'Confirmar operación',exact:true}).click();
 await page.getByRole('button',{name:'Crear unión',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Editar unión'});await dialog.getByLabel('Tipo de unión').selectOption('Tornillos');await dialog.getByLabel('Cantidad',{exact:true}).fill('4');await dialog.getByLabel('Diámetro (mm)',{exact:true}).fill('4');await dialog.getByLabel('Longitud (mm)',{exact:true}).fill('40');await dialog.getByLabel('Notas').fill('Ensayo de montaje');await dialog.getByRole('button',{name:'Guardar unión',exact:true}).click();
 project=await read(page);expect(project.joins).toHaveLength(1);expect(project.pieces.flatMap((p:any)=>p.operations??[])).toHaveLength(3);await page.keyboard.press('Control+z');expect((await read(page)).joins??[]).toHaveLength(0);await page.keyboard.press('Control+Shift+z');expect((await read(page)).joins).toHaveLength(1);
 await page.getByRole('button',{name:'＋ Material a medida',exact:true}).click();await page.getByLabel('Nombre del material').fill('Pino especial');await page.getByLabel('Largo del material').fill('2000');await page.getByRole('button',{name:'Guardar material',exact:true}).click();expect((await read(page)).customMaterials).toHaveLength(1);
 await page.getByLabel('Buscar material').fill('MDF');await page.locator('.material-card').first().click();await cut(page,800);await cut(page,400,true);
 await page.getByRole('button',{name:'⌒ Formas curvas',exact:true}).click();await page.getByLabel('Forma curva',{exact:true}).selectOption('circle');await page.getByRole('button',{name:'Confirmar operación',exact:true}).click();
 await view(page,'Fabricación');await page.getByLabel('Ancho de corte de sierra (kerf)',{exact:true}).fill('3');await page.getByLabel('Ancho de corte de sierra (kerf)',{exact:true}).press('Enter');await expect(page.locator('.manufacturing .assembly-section')).toContainText('4 × Tornillos');await page.getByRole('button',{name:'Optimizar material',exact:true}).click();await page.getByRole('button',{name:'Generar reporte',exact:true}).click();const report=page.getByRole('dialog',{name:'Reporte de fabricación'});await expect(report).toContainText('Plan optimizado');await expect(report).toContainText('Ensayo de montaje');await expect(report).toContainText('Corte angular 45°');
 const download=page.waitForEvent('download',{timeout:20000});await report.getByRole('button',{name:'Exportar PDF',exact:true}).click();await (await download).saveAs('output/pdf/fase7-taller.pdf');
 await page.evaluate(()=>{(window as any).__printed=false;window.print=()=>{(window as any).__printed=true;};});await report.getByRole('button',{name:'Imprimir',exact:true}).click();expect(await page.evaluate(()=>(window as any).__printed)).toBe(true);await page.emulateMedia({media:'print'});await expect(page.locator('#root')).toBeHidden();await expect(report).toBeVisible();await page.screenshot({path:'tests/phase7-print.png',fullPage:true});await page.emulateMedia({media:'screen'});await report.getByRole('button',{name:'Cerrar reporte',exact:true}).click();
 const saved=await read(page);await page.reload();await expect(page.locator('.piece-row')).toHaveCount(saved.pieces.length);expect(await read(page)).toEqual(saved);await view(page,'Fabricación');await expect(page.locator('.manufacturing .assembly-section')).toContainText('Ensayo de montaje');await page.screenshot({path:'tests/phase7-manufacturing.png',fullPage:true});expect(errors).toEqual([]);
});
