import { test, expect, type Page } from '@playwright/test';
import { readFileSync } from 'node:fs';
test.use({channel:'msedge',viewport:{width:1440,height:1000}});
const read=(page:Page)=>page.evaluate(()=>JSON.parse(localStorage.getItem('taller-project-v1')!));
const view=(page:Page,name:string)=>page.getByRole('group',{name:'Vista principal',exact:true}).getByRole('button',{name,exact:true}).click();
async function template(page:Page,name:string){await page.getByLabel('Categoría del material').selectOption('Plantillas');await page.getByLabel('Plantilla',{exact:true}).selectOption(name);await page.getByRole('button',{name:'Crear plantilla',exact:true}).click();await expect(page.locator('.template-catalog [role=alert]')).toHaveCount(0);}
test('plantillas editables: mesa, repisa y cajonera',async({page})=>{test.setTimeout(90000);await page.goto('http://127.0.0.1:5173');for(const [name,count] of [['Mesa',5],['Repisa',3],['Cajonera',20]] as const){await page.getByRole('button',{name:'＋ Nuevo',exact:true}).click();await template(page,name);expect((await read(page)).pieces.filter((p:any)=>p.usage==='used')).toHaveLength(count);await page.waitForTimeout(1400);await page.screenshot({path:'tests/phase8-'+name+'.png'});}});
test('v1: selección, herramienta visual, unión, reporte y archivo portable',async({page})=>{test.setTimeout(120000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5173');await template(page,'Mesa');
 const project=await read(page),used=project.pieces.filter((p:any)=>p.usage==='used');
 const choose=(code:string)=>page.locator('.piece-select').filter({hasText:code+' ·'});
 await choose(used[0].code).click();await choose(used[1].code).click({modifiers:['Shift']});await expect(page.locator('.interaction-toolbar')).toContainText('2 piezas');await page.getByRole('button',{name:'Agrupar',exact:true}).click();await page.keyboard.press('ArrowRight');await page.keyboard.press('Shift+ArrowUp');let moved=await read(page);for(const p of used.slice(0,2))expect(moved.pieces.find((v:any)=>v.id===p.id).position).toEqual([p.position[0]+1,p.position[1],p.position[2]+10]);await page.keyboard.press('Control+z');await page.keyboard.press('Control+z');expect((await read(page)).pieces).toEqual(project.pieces);
 await choose(used[0].code).click();await page.getByRole('button',{name:'Desagrupar',exact:true}).click();await choose(used[0].code).click();
 await page.getByRole('button',{name:'✂ Cortar',exact:true}).click();await page.locator('.cut-measure').click();await page.getByLabel('Medida de corte',{exact:true}).fill('720');await page.getByLabel('Medida de corte',{exact:true}).press('Enter');await page.getByRole('button',{name:'✓ Confirmar corte',exact:true}).click();
 await page.getByLabel('Vista',{exact:true}).selectOption('Superior');await page.waitForTimeout(1600);
 await page.getByRole('button',{name:'◎ Perforar',exact:true}).click();await page.getByRole('button',{name:'Ø8',exact:true}).click();const box=(await page.locator('canvas').boundingBox())!;const x=box.x+box.width/2-110,y=box.y+box.height/2;await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x-35,y+25,{steps:6});await page.mouse.up();await expect(page.locator('.snap-tag').filter({hasText:'Ø8'})).toBeVisible();await page.screenshot({path:'tests/phase8-drill.png'});await page.getByRole('button',{name:'Confirmar operación',exact:true}).click();
 expect((await read(page)).pieces.flatMap((p:any)=>p.operations??[])).toHaveLength(1);
 await page.getByRole('button',{name:'Unir',exact:true}).click();await page.mouse.click(x-65,y+50);await expect(page.locator('.tool-hint')).toContainText('otra pieza');await page.mouse.click(box.x+box.width/2+150,y);await expect(page.getByRole('dialog',{name:'Editar unión'})).toBeVisible();await page.getByLabel('Tipo de unión').selectOption('Tornillos');await page.getByLabel('Cantidad',{exact:true}).fill('4');await page.getByRole('button',{name:'Guardar unión',exact:true}).click();expect((await read(page)).joins).toHaveLength(1);
 await page.getByRole('button',{name:'Medir',exact:true}).click();await page.mouse.click(x-65,y+50);await page.mouse.click(x-90,y+25);await expect(page.locator('.snap-tag.captured').filter({hasText:/mm$/})).toBeVisible();await page.keyboard.press('Escape');
 await view(page,'Fabricación');await page.getByRole('button',{name:'Optimizar material',exact:true}).click();await page.locator('.manufacturing').evaluate(el=>{el.scrollTop=100;});await page.getByRole('button',{name:'Generar reporte',exact:true}).click();await expect(page.getByRole('dialog',{name:'Reporte de fabricación'})).toBeVisible();const scroll=await page.locator('.manufacturing').evaluate(el=>el.scrollTop);await page.keyboard.press('Escape');await expect(page.getByRole('dialog',{name:'Reporte de fabricación'})).toHaveCount(0);expect(await page.locator('.manufacturing').evaluate(el=>el.scrollTop)).toBe(scroll);await page.getByRole('button',{name:'Generar reporte',exact:true}).click();await page.getByRole('button',{name:'Cerrar reporte',exact:true}).click();
 await page.getByRole('button',{name:'Exportar .crj',exact:true}).click();await page.getByLabel('Nombre del proyecto',{exact:true}).fill('MiMesa');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Guardar archivo .crj',exact:true}).click();await (await download).saveAs('output/MiMesa.crj');const saved=await read(page);expect(JSON.parse(readFileSync('output/MiMesa.crj','utf8')).project).toEqual(saved);
 await page.getByRole('button',{name:'＋ Nuevo',exact:true}).click();expect((await read(page)).pieces).toHaveLength(0);await page.getByLabel('Abrir archivo de proyecto',{exact:true}).setInputFiles('output/MiMesa.crj');await expect.poll(async()=>await read(page)).toEqual(saved);await view(page,'Diseño');await choose(saved.pieces.find((p:any)=>p.usage==='used').code).click();await page.keyboard.press('ArrowRight');expect((await read(page)).pieces).not.toEqual(saved.pieces);await page.reload();await expect(page.locator('.piece-row')).toHaveCount(saved.pieces.length);expect(errors).toEqual([]);
});

test('arrastre múltiple sin desplazamiento residual; enfoque, cotas y menú contextual',async({page})=>{
 test.setTimeout(60000);await page.goto('http://127.0.0.1:5173');await template(page,'Mesa');const before=await read(page),pieces=before.pieces.filter((p:any)=>p.usage==='used');
 await page.getByLabel('Vista',{exact:true}).selectOption('Superior');await page.waitForTimeout(1500);
 for(let i=0;i<pieces.length;i++)await page.locator('.piece-select').filter({hasText:pieces[i].code+' ·'}).click({modifiers:i?['Shift']:[]});
 const box=(await page.locator('canvas').boundingBox())!,x=box.x+box.width/2-70,y=box.y+box.height/2-30;
 await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+45,y-20,{steps:10});await page.mouse.up();
 const after=await read(page),delta=after.pieces.find((p:any)=>p.id===pieces[0].id).position.map((n:number,i:number)=>n-pieces[0].position[i]);expect(Math.hypot(...delta)).toBeGreaterThan(10);
 for(const p of pieces)after.pieces.find((n:any)=>n.id===p.id).position.forEach((n:number,i:number)=>expect(n-p.position[i]).toBeCloseTo(delta[i],4));
 expect(await page.evaluate(async()=>{const path='/src/interaction/store.ts';return (await import(path)).useTools.getState().drag;})).toBeNull();
 await page.keyboard.press('Control+z');expect((await read(page)).pieces).toEqual(before.pieces);
 await page.mouse.click(x,y,{button:'right'});await expect(page.getByRole('menu')).toBeVisible();await page.getByRole('menuitem',{name:'Enfocar',exact:true}).click();await expect(page.getByRole('menu')).toHaveCount(0);
 await page.getByRole('button',{name:'⊡ Ajustar todo',exact:true}).click();await page.waitForTimeout(1200);await page.mouse.dblclick(x,y);await page.waitForTimeout(1000);
 expect(await page.evaluate(async()=>{const path='/src/interaction/store.ts';return (await import(path)).useTools.getState().focus.id;})).toBe(pieces[0].id);
 await page.getByLabel('Cotas de selección',{exact:true}).uncheck();await expect(page.locator('.dimension-tag')).toHaveCount(0);
});
