import { useEffect } from 'react';
import { ANGULAR_GUIDES } from '../model';
import { faceFrame,faceNames,faceReference,operationError } from '../operations/geometry';
import { useOperation } from '../operations/store';
import { useEditor } from '../store';
import type { Face } from '../operations/types';
export function OperationBar(){const s=useOperation(),project=useEditor(x=>x.project),p=project.pieces.find(p=>p.id===s.pieceId),op=s.draft;
    useEffect(()=>{const key=(e:KeyboardEvent)=>{if(useOperation.getState().pieceId&&e.key==='Escape'){e.preventDefault();e.stopPropagation();useOperation.getState().cancel();}};window.addEventListener('keydown',key,true);return()=>window.removeEventListener('keydown',key,true);},[]);
    if(!p||!op)return null;const error=operationError(p,op);
    const field=(label:string,key:string,value:number,min=0,max?:number)=><label>{label}<input aria-label={label} type="number" step="any" min={min} max={max} value={Number.isFinite(value)?value:''} onChange={e=>s.patch({[key]:e.target.value===''?NaN:Number(e.target.value)})}/></label>;
    return <div className="operation-bar" role="region" aria-label="Operación especial"><b>{op.kind==='angular'?'Corte angular · acabado de la base':op.kind==='drill'?'Perforar':'Forma curva'}</b>
        {op.kind==='angular'&&<><label>Dimensión<select aria-label="Dimensión angular" value={op.axis} onChange={e=>s.patch({axis:e.target.value,offset:p[e.target.value as 'length'|'width']/2})}><option value="length">Largo</option><option value="width">Ancho</option></select></label>{field('Posición de corte (mm)','offset',op.offset,1,p[op.axis]-1)}{field('Ángulo de corte (°)','angle',op.angle,-90,90)}<div className="angle-presets">{ANGULAR_GUIDES.map(a=><button key={a} onClick={()=>s.patch({angle:a})}>{a}°</button>)}</div><label>Conservar<select aria-label="Lado conservado" value={op.keep} onChange={e=>s.patch({keep:e.target.value})}><option value="start">Lado inicial</option><option value="end">Lado final</option></select></label><small>La base rectangular conserva su ID. El acabado se detalla aparte en el reporte; no crea un sobrante rectangular.</small></>}
        {op.kind==='drill'&&<><p>Haz clic en una cara para colocar el centro. {faceReference(op.face)}</p><details className="drill-exact"><summary>Posición exacta / cara</summary><label>Cara<select aria-label="Cara de perforación" value={op.face} onChange={e=>{const face=e.target.value as Face,f=faceFrame(p,face);s.patch({face,u:f.maxU/2,v:f.maxV/2,depth:Math.min(op.depth,f.depth)});}}>{Object.entries(faceNames).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label>{field('Centro horizontal (mm)','u',op.u)}{field('Centro vertical (mm)','v',op.v)}</details><div className="drill-presets">{[5,8,10,35].map(d=><button key={d} aria-pressed={op.diameter===d} onClick={()=>s.patch({diameter:d})}>Ø{d}</button>)}<button onClick={()=>document.querySelector<HTMLInputElement>('.operation-bar input[aria-label="Diámetro (mm)"]')?.focus()}>Personalizado</button></div>{field('Diámetro (mm)','diameter',op.diameter,1)}{field('Profundidad (mm)','depth',op.depth,1,faceFrame(p,op.face).depth)}</>}
        {op.kind==='curve'&&<><label>Forma<select aria-label="Forma curva" value={op.shape} onChange={e=>s.patch({shape:e.target.value})}><option value="round-corner">Esquina redondeada</option><option value="arc">Arco en extremo final</option><option value="semicircle">Semicírculo</option><option value="circle">Círculo / agujero</option></select></label>{field('Radio (mm)','radius',op.radius,1)}{op.shape==='round-corner'?<label>Esquina<select aria-label="Esquina" value={op.corner} onChange={e=>s.patch({corner:e.target.value})}><option value="near-left">Cercana inicial</option><option value="near-right">Cercana final</option><option value="far-left">Lejana inicial</option><option value="far-right">Lejana final</option></select></label>:['circle','semicircle'].includes(op.shape)&&<>{field('Centro en largo (mm)','u',op.u)}{field('Centro en ancho (mm)','v',op.v)}</>}<small>Forma sobre la cara superior de la base. Las medidas comerciales no cambian.</small></>}
        {error&&<span className="operation-error" role="status">{error}</span>}<div><button disabled={!!error} onClick={s.confirm}>Confirmar operación</button><button onClick={s.cancel}>Cancelar operación</button></div>
    </div>;
}
