import { createPortal } from 'react-dom';
import { useEffect, useRef, useState } from 'react';
import { useEditor } from '../store';
import { planIsStale } from '../optimization/supplies';
import { buildReport, reportPurchases, type WorkshopReport } from '../report/model';
import { dimensions, type Piece } from '../model';
import { describeOperation, outline } from '../operations/geometry';
function FinishDiagram({piece}:{piece:Piece}){const poly=outline(piece),x=Math.min(...poly.map(p=>p[0])),y=Math.min(...poly.map(p=>p[1])),w=Math.max(...poly.map(p=>p[0]))-x,h=Math.max(...poly.map(p=>p[1]))-y,pad=Math.max(w,h)*.01;return <svg viewBox={[x-pad,y-pad,w+2*pad,h+2*pad].join(' ')} role="img" aria-label="Contorno final de la pieza"><polygon points={poly.map(p=>p.join(',')).join(' ')} fill="#daebf6" stroke="#6f899b" strokeWidth={1} vectorEffect="non-scaling-stroke"/>{piece.operations?.map(op=>op.kind==='curve'&&op.shape==='circle'?<circle key={op.id} cx={op.u} cy={op.v} r={op.radius} fill="white" stroke="#9a5317" vectorEffect="non-scaling-stroke"/>:op.kind==='drill'&&['top','bottom'].includes(op.face)?<circle key={op.id} cx={op.u} cy={op.v} r={op.diameter/2} fill="none" stroke="#9a5317" vectorEffect="non-scaling-stroke"/>:null)}</svg>;}
export function ReportButton(){const project=useEditor(s=>s.project),[open,setOpen]=useState(false),[report,setReport]=useState<WorkshopReport|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
    const returnFocus=useRef<HTMLElement|null>(null);
    useEffect(()=>{if(!open)return;returnFocus.current=document.activeElement as HTMLElement;const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();setOpen(false);}};window.addEventListener('keydown',key);document.querySelector<HTMLButtonElement>('.report-close')?.focus();return()=>{window.removeEventListener('keydown',key);returnFocus.current?.focus({preventScroll:true});};},[open]);
    const warning=!!project.optimizedPlan&&(planIsStale(project)||project.optimizedPlan.unplaced.length>0);
    const generate=(mode:'current'|'optimized')=>{setReport(buildReport(project,mode));setOpen(true);setError('');};
    const download=async()=>{if(!report)return;setBusy(true);try{const {createReportPdf}=await import('../report/pdf');createReportPdf(report).save('reporte-taller.pdf');}catch{setError('No se pudo generar el PDF. Intenta nuevamente.');}finally{setBusy(false);}};
    return <><button onClick={()=>{if(warning){setReport(null);setOpen(true);}else generate(project.optimizedPlan?'optimized':'current');}}>Generar reporte</button>
        {open&&createPortal(<div className="report-overlay"><section className="report-document" role="dialog" aria-modal="true" aria-label="Reporte de fabricación"><button className="report-close" aria-label="Cerrar reporte" title="Cerrar (Esc)" onClick={()=>setOpen(false)}>×</button><div className="report-actions">{report&&<><button disabled={busy} onClick={download}>{busy?'Generando PDF…':'Exportar PDF'}</button><button onClick={()=>window.print()}>Imprimir</button></>}</div>
            {!report?<><h2>Revisar plan antes de generar</h2><p role="alert">El plan optimizado está desactualizado o incompleto. Vuelve a optimizar para usarlo en el reporte.</p><button onClick={()=>{useEditor.getState().optimize();const p=useEditor.getState().project;if(p.optimizedPlan&&!p.optimizedPlan.unplaced.length)setReport(buildReport(p,'optimized'));else setError('Hay piezas sin ubicar. Revisa la propuesta o genera el plan actual.');}}>Optimizar y generar</button><button onClick={()=>generate('current')}>Generar con plan actual</button></>:<><h1>Reporte de fabricación</h1><p>{report.project} · {report.date} · {report.mode==='optimized'?'Plan optimizado':'Plan actual'}</p><p>Unidades: mm · Sierra de referencia: {report.kerf} mm</p><h2>Lista de material</h2>{reportPurchases(report).map(p=><p key={p.label}>{p.quantity} × {p.label}</p>)}{report.stocks.filter(s=>s.reused).map(s=><p key={s.name}>Reutilizar {s.reused}: {dimensions(s)}</p>)}<h2>Lista de piezas</h2><table><thead><tr><th>IDs</th><th>Material</th><th>Base rectangular (mm)</th><th>Cantidad</th></tr></thead><tbody>{report.pieces.map(p=><tr key={p.codes.join(',')}><td>{p.codes.join(', ')}</td><td>{p.material}</td><td>{dimensions(p)}</td><td>{p.quantity}</td></tr>)}</tbody></table>
            {report.stocks.map(s=><section className="report-sheet" key={s.name}><h2>{s.name} - {s.material}</h2><p>{dimensions(s)} · {s.reused??'Material comercial'}</p><svg viewBox={`0 0 ${s.length} ${s.sheet?s.width:Math.max(s.width,s.length*.14)}`} role="img" aria-label={`Reporte ${s.name}`}>{s.cells.map((c,i)=>{const sy=s.sheet?1:Math.max(s.width,s.length*.14)/s.width,fs=s.length/65;return <g key={i}><rect x={c.x} y={c.y*sy} width={c.length} height={c.width*sy} fill={c.available?'#edf4dd':'#daebf6'} stroke="#6f899b" strokeWidth={1} vectorEffect="non-scaling-stroke"/>{c.length>fs*5&&c.width*sy>fs*3&&<text x={c.x+c.length/2} y={(c.y+c.width/2)*sy} textAnchor="middle" fontSize={fs}>{c.label}<tspan x={c.x+c.length/2} dy={fs*1.4}>{c.length} × {c.width}</tspan></text>}</g>;})}{s.cuts.map((c,i)=>{const sy=s.sheet?1:Math.max(s.width,s.length*.14)/s.width;return <rect key={i} x={c.x} y={c.y*sy} width={Math.max(c.length,.8)} height={Math.max(c.width*sy,.8)} fill="#c3944b"/>;})}</svg><p>Azul: piezas; verde: disponible; líneas ocre: sierra. Diagrama no a escala 1:1.</p>{s.cells.map((c,i)=><p key={i}>{c.label}{c.rotated?' (girada 90°)':''}: {c.length} × {c.width} × {s.height} mm</p>)}<ol>{s.cuts.map((c,i)=><li key={i}>{c.code}: dividir {c.axis==='length'?'largo':'ancho'} a {c.offset} mm; sierra {c.kerf} mm.</li>)}</ol></section>)}
            {report.specials.map(s=><section className="report-sheet" key={s.code}><h2>Operaciones especiales - {s.code}</h2><p>Base {dimensions(s.piece)}. Las medidas de acabado se toman antes de girar la base en el plan.</p><FinishDiagram piece={s.piece}/>{s.operations.map(op=><p key={op.id}>{describeOperation(op)}</p>)}</section>)}
            {!!report.assembly.length&&<section className="report-sheet"><h2>Uniones / Ensamble</h2>{report.assembly.map((j,i)=><article key={i}><h3>{j.pieces}</h3><p>Caras: {j.faces}</p><p>{j.description}</p>{j.review&&<p>REVISAR: {j.review}</p>}</article>)}</section>}
            </>}{error&&<p role="alert">{error}</p>}
        </section></div>,document.body)}
    </>;
}
