import { nearestFaces, joinEnd, joinReview } from '../assembly/model';
import { beforeEach, expect, it } from 'vitest';
import { useEditor, selectionIds, validProject } from '../store';
import { catalog } from '../model';
import { buildTemplate, templates, templateDefaults } from '../templates/build';
import { decodeProject, encodeProject } from './file';
import { solvePlacement, alignContact } from '../snap/placement';
import { bodyFor } from '../snap/geometry';
import { optimizeProject } from '../optimization/optimize';
const state=()=>useEditor.getState();
beforeEach(()=>useEditor.setState({project:{version:1,name:'Mesa v1',pieces:[]},selected:null,selectedIds:[],groups:[],past:[],future:[]}));
it.each(templates)('generates editable %s with valid provenance and normal cuts',kind=>{const project=buildTemplate(state().project,kind,...templateDefaults[kind],catalog.find(m=>m.id==='mdf-18')!);expect(validProject(project)).toBe(true);expect(project.pieces.filter(p=>p.usage==='used').length).toBeGreaterThan(2);expect(project.pieces.filter(p=>p.usage==='available').every(p=>p.isHidden)).toBe(true);state().loadProject(project);const p=state().project.pieces.find(p=>p.usage==='used')!;state().cut(p.id,p.length/2);expect(state().project.cuts!.length).toBeGreaterThan(project.cuts!.length);state().undo();expect(state().project).toEqual(project);});
it('retains the complete project in a portable file, rejects damaged data without replacing the current design',()=>{let project=buildTemplate(state().project,'Mesa',1200,750,700,catalog[3]);state().loadProject(project);const p=state().project.pieces.find(p=>p.usage==='used')!;state().addOperation(p.id,{id:'hole',kind:'drill',face:'top',u:100,v:100,diameter:8,depth:18});state().setPreferences({grid:false,shadows:true,dimensions:false,snapAlignment:'center'});project={...state().project,optimizedPlan:optimizeProject(state().project)};expect(decodeProject(encodeProject(project))).toEqual(project);expect(()=>decodeProject('{bad')).toThrow();expect(()=>decodeProject(JSON.stringify({format:'taller-crj',fileVersion:99,project}))).toThrow();expect(state().loadProject({version:99} as never)).toBe(false);expect(state().project.pieces).toHaveLength(project.pieces.length);});
it('moves a selection as one history entry, maintains temporary groups, and respects locked members',()=>{state().add('pino-100');const a=state().selected!;state().add('pino-100');const b=state().selected!;state().select(a);state().select(b,true);expect(selectionIds(state())).toEqual([a,b]);state().group();const before=state().project;const p=before.pieces.find(p=>p.id===b)!;state().update(b,{position:[p.position[0]+10,p.position[1]+20,p.position[2]+30]});for(const original of before.pieces)expect(state().project.pieces.find(p=>p.id===original.id)!.position).toEqual(original.position.map((n,i)=>n+[10,20,30][i]));state().undo();expect(state().project).toEqual(before);state().redo();state().select(a);expect(selectionIds(state())).toHaveLength(2);state().ungroup();state().select(a);expect(selectionIds(state())).toEqual([a]);});
it('free face snap preserves both tangential coordinates; explicit alignment remains available',()=>{state().add('pino-100');const base=state().project.pieces[0],target={...base,id:'t',length:200,width:100,height:100,position:[0,50,0] as [number,number,number]},p={...target,id:'m',position:[208,54,3] as [number,number,number]};const free=solvePlacement(p,[bodyFor(target)]);expect(free.position).toEqual([200,54,3]);const centered=solvePlacement(p,[bodyFor(target)],[true,true,true],undefined,'center');expect(centered.position).toEqual([200,50,0]);expect(free.face?.captured).toBe(true);});

it('post-contact alignment centers or aligns edges without separating the face planes',()=>{state().add('pino-100');const p=state().project.pieces[0],target={...p,id:'target',length:200,width:200,height:100,position:[0,50,0] as [number,number,number]},moving={...target,id:'moving',width:80,position:[200,65,45] as [number,number,number]};const targets=[bodyFor(target)];expect(alignContact(moving,targets,'center').position).toEqual([200,50,0]);expect(alignContact(moving,targets,'min').position).toEqual([200,50,-60]);expect(alignContact(moving,targets,'max').position).toEqual([200,50,60]);});

it('suggests the faces already in contact even when their centers are farther apart',()=>{const p=buildTemplate(state().project,'Mesa',1200,750,700,catalog[3]),pieces=p.pieces.filter(p=>p.usage==='used'),a=pieces[0],b=pieces[1],[af,bf]=nearestFaces(a,b);expect(joinReview(p,{id:'suggestion',a:joinEnd(a,af),b:joinEnd(b,bf),type:'Sin especificar'})).toBeNull();});
